### ISSUE TITLE
Crash up on pressing settings tab

### ISSUE THREAD

**Issue by CustomIcon** [TheGreyRaven/SnapTrap#2]
![Screenshot_2022-02-07-18-47-37-729_com miui bugreport](https://user-images.githubusercontent.com/43902347/152800639-e03fc55f-8dce-4531-a6bd-7f39c553bbfa.jpg)
seems like its still searching for old xposed installer class which is not available in lsposed. i can't seem to access settings without snaptrap getting crashed

**Comment by TheGreyRaven** [comment]
The settings page is broken and have nothing to with any missing classes.
In the SnapTrap folder you have a .JSON file which contains the settings, edit that file and you can enable and disable different settings.
